Repository AliceLR/megazeux, pull requests merged in 2019-07, with the labels that each got.

#185 Add SAVE_ROBOT for string, implement debytecode SAVE_ROBOT
  docs/changelog.txt
  src/counter.c
  src/counter_struct.h
  src/editor/robo_debug.c
  src/editor/robot.c
  src/error.c
  src/legacy_rasm.c
  src/legacy_rasm.h
  src/legacy_robot.c
  src/rasm.c
  src/rasm.h
  src/robot.c
  src/robot.h
  src/robot_struct.h
  src/str.c
  src/world_format.h
  testworlds/2.51/006 ZAP RESTORE.mzx
  testworlds/2.51/006 ZAP RESTORE.txt
  testworlds/2.70/002 LOAD_ROBOT.mzx
  testworlds/2.81/b00 SAVE_GAME pos.mzx
  testworlds/2.81/b01 SAVE_GAME ZAP.mzx
  testworlds/2.84/002 Load 2.84 Save.mzx
  testworlds/2.92/007 SAVE_ROBOTn str.mzx
  testworlds/data/saved.284c.sav
  testworlds/run.sh
  testworlds/tests.mzx
Labels: Platform: All, enhancement

#186 Add experimental OpenBSD pledge(2) support, fix some compile warnings
  Makefile
  config.sh
  docs/changelog.txt
  src/compat.h
  src/fsafeopen.c
  src/legacy_world.c
  src/main.c
  src/settings.c
  src/util.c
  src/utils/ccv.c
  src/utils/checkres.c
  src/utils/downver.c
  src/utils/hlp2html.c
  src/utils/hlp2txt.c
  src/utils/png2smzx.c
  src/utils/txt2hlp.c
  src/window.c
  src/zip.c
Labels: Platform: OpenBSD, enhancement

#183 Palette editor improvements
  docs/changelog.txt
  src/editor/edit.c
  src/editor/graphics.c
  src/editor/graphics.h
  src/editor/pal_ed.c
  src/editor/pal_ed.h
  src/graphics.h
Labels: Platform: All, enhancement

#187 Improve joystick actions
  arch/3ds/event.c
  arch/3ds/pad.config
  arch/3ds/platform.c
  arch/gp2x/pad.config
  arch/nds/event.c
  arch/nds/pad.config
  arch/psp/pad.config
  arch/wii/event.c
  arch/wii/pad.config
  config.txt
  docs/changelog.txt
  src/configure.c
  src/core.c
  src/counter.c
  src/event.c
  src/event.h
  src/event_sdl.c
  src/game.c
  src/game_menu.c
  src/game_menu.h
  src/game_player.c
  src/keysym.h
  src/main.c
  src/platform_sdl.c
  src/window.c
  src/world.c
  src/world_format.h
  src/world_struct.h
Labels: Platform: All, enhancement

#169 [WIP] Emscripten port
  arch/emscripten/Makefile.in
  arch/emscripten/whitelist.json
  config.sh
  contrib/libxmp/Makefile.megazeux
  docs/platform_matrix.html
  src/Makefile.in
  src/audio/audio_sdl.c
  src/configure.c
  src/core.c
  src/error.c
  src/graphics.c
  src/platform_sdl.c
  src/render_glsl.c
  src/render_layer.c
  src/render_sdl.c
  src/settings.c
Labels: Platform: Emscripten, enhancement

#188 Fix several RAD player/validator bugs
  contrib/rad/README.md
  contrib/rad/player20.cpp
  contrib/rad/validate20.cpp
  testworlds/2.92/002 RAD.mzx
  testworlds/data/audio/Shayde - Canon in D.rad
Labels: Introduced in GIT, Platform: All, bug
