Repository AliceLR/megazeux, pull requests merged in 2020-10, with the labels that each got.

#272 Fix SAM frequency bug caused by handling SAMs like 16-bit samples
  docs/changelog.txt
  src/audio/audio.c
  src/audio/audio.h
  src/audio/audio_wav.c
  src/audio/audio_xmp.c
Labels: Introduced in 2.80X, Platform: All, bug

#273 Fix MikMod ST .MOD support, MOD_POSITION/MOD_LENGTH, and more.
  config.sh
  docs/changelog.txt
  src/audio/audio_mikmod.c
Labels: Introduced in 2.81X, Platform: All, bug

#275 Fix `restrict` define for MSVC
  docs/STYLE.md
  src/compat.h
  src/render.c
  src/render.h
  src/render_layer.cpp
  src/render_layer.h
  src/render_layer_code.hpp
  src/render_softscale.c
  src/render_yuv.c
Labels: Introduced in GIT, Platform: Windows, bug

#276 MSVC Project Update (October 2020)
  arch/msvc/Core.vcxproj
  arch/msvc/Core.vcxproj.filters
Labels: Platform: Windows, enhancement

#277 Update libxmp to master e6e28ade.
  contrib/libxmp/Makefile.megazeux
  contrib/libxmp/Makefile.megazeux-gen
  contrib/libxmp/README.megazeux.md
  contrib/libxmp/docs/Changelog
  contrib/libxmp/src/hio.c
  contrib/libxmp/src/hio.h
  contrib/libxmp/src/load.c
  contrib/libxmp/src/load_helpers.c
  contrib/libxmp/src/loaders/amf_load.c
  contrib/libxmp/src/loaders/iff.c
  contrib/libxmp/src/loaders/med4_load.c
  contrib/libxmp/src/loaders/stm_load.c
  contrib/libxmp/src/mdataio.h
  contrib/libxmp/src/memio.c
  contrib/libxmp/src/xfnmatch.c
  contrib/libxmp/src/xfnmatch.h
  contrib/patches/libxmp/01-libxmp-mingw-snprintf.patch
  contrib/patches/libxmp/01-libxmp-mzx-integration.patch
  contrib/patches/libxmp/02-libxmp-mzx-remove-extra-formats.patch
  contrib/patches/libxmp/02-libxmp-remove-depackers.patch
  contrib/patches/libxmp/10-libxmp-fix-load-module-from-file.patch
  contrib/patches/libxmp/11-libxmp-fix-set-position-jump.patch
  contrib/patches/libxmp/13-libxmp-fix-s3m-adpcm.patch
  contrib/patches/libxmp/14-libxmp-fix-gdm-fine-effects.patch
  contrib/patches/libxmp/15-libxmp-fix-st-2-zero-volume-samples.patch
  contrib/patches/libxmp/16-libxmp-fix-far-volume.patch
  contrib/patches/libxmp/17-libxmp-fix-med-compat-tempos.patch
  contrib/patches/libxmp/README
  src/audio/audio_xmp.c
Labels: Platform: All, enhancement
