Repository AliceLR/megazeux, pull requests merged in 2020-09, with the labels that each got.

#251 NDS port improvements
  arch/nds/Makefile.in
  arch/nds/arm7/Makefile
  arch/nds/arm7/source/arm7main.c
  arch/nds/audio.c
  arch/nds/exception.c
  arch/nds/gen_protected_palette.py
  arch/nds/platform.c
  arch/nds/platform.h
  arch/nds/protected_palette.bin
  arch/nds/render.c
  arch/nds/render.h
  arch/nds/thread.h
  config.sh
  scripts/deps/nds.zip
  scripts/msys2-cross-scripts/dk-nds-dependencies.sh
  src/Makefile.in
  src/audio/audio.c
  src/audio/sfx.c
  src/event.h
  src/graphics.c
  src/graphics.h
  src/platform.h
  src/util.h
  src/window.c
Labels: Platform: Nintendo DS, enhancement

#259 Make active UI elements use cursor_hint
  config.txt
  src/configure.c
  src/configure.h
  src/editor/window.c
  src/game_menu.c
  src/graphics.c
  src/graphics.h
  src/helpsys.c
  src/robot.c
  src/scrdisp.c
  src/settings.c
  src/window.c
  unit/configure.cpp
Labels: Platform: All, enhancement

#262 Netcode C++ refactor III: Legion (of bad code)
  docs/changelog.txt
  src/network/HTTPHost.cpp
  src/network/HTTPHost.hpp
  src/network/Manifest.cpp
  src/network/Scoped.hpp
  src/updater.cpp
Labels: Platform: Windows, enhancement

#263 Implement SOCKS5 IPv6 support, username/password auth
  config.txt
  docs/changelog.txt
  src/configure.c
  src/configure.h
  src/network/Host.cpp
  src/network/Host.hpp
  src/network/Socket.hpp
  unit/configure.cpp
Labels: Platform: All, bug, enhancement

#264 Add config.sh flags `--disable-getaddrinfo` and `--disable-ipv6`
  arch/psp/Makefile.in
  arch/wii/Makefile.in
  arch/wii/network.cpp
  config.sh
  docs/changelog.txt
  src/Makefile.in
  src/network/DNS.cpp
  src/network/Host.cpp
  src/network/Socket.cpp
  src/network/Socket.hpp
Labels: Platform: Amiga OS 4, Platform: Nintendo Wii, Platform: Nintendo Wii U, Platform: PlayStation Portable, enhancement

#265 Implement Wii network support.
  arch/wii/network.cpp
  src/network/Host.cpp
  src/network/Host.hpp
  src/network/Socket.cpp
  src/network/Socket.hpp
  src/updater.cpp
Labels: Platform: Nintendo Wii, enhancement

#261 Add editor show thing config options
  config.txt
  docs/changelog.txt
  src/editor/configure.c
  src/editor/configure.h
  src/editor/edit.c
  unit/configure.cpp
Labels: Platform: All, enhancement

#266 Replace unimplemented thread.h message with error attributes
  arch/nds/thread.h
  src/platform.h
  src/thread_dummy.h
Labels: Platform: All, enhancement

#268 Split SUPPRESS_BUILD into several flags, use with "make dist"
  Makefile
  arch/3ds/Makefile.in
  arch/android/Makefile.in
  arch/darwin/Makefile.in
  arch/emscripten/Makefile.in
  arch/gp2x/Makefile.in
  arch/mingw/Makefile.in
  arch/nds/Makefile.in
  arch/none/Makefile.in
  arch/psp/Makefile.in
  arch/switch/Makefile.in
  arch/wii/Makefile.in
  docs/changelog.txt
Labels: Introduced in 2.82X, Platform: Android, Platform: MacOS, bug

#267 Implement 3DS and Switch network support.
  arch/wii/network.cpp
  config.sh
  docs/changelog.txt
  src/network/Host.cpp
  src/network/Socket.cpp
  src/network/Socket.hpp
Labels: Platform: Nintendo 3DS, Platform: Nintendo Switch, enhancement

#269 Add joystick config unit test, fix joystick ranges for NDS/3DS
  src/event.c
  src/event.h
  unit/configure.cpp
Labels: Introduced in GIT, Platform: Nintendo 3DS, Platform: Nintendo DS, bug

#270 Fix audio.c, sfx.c threading issues and PC speaker note cancelling
  arch/nds/audio.c
  docs/changelog.txt
  src/audio/audio.c
  src/audio/audio.h
  src/audio/audio_pcs.c
  src/audio/sfx.c
  src/audio/sfx.h
  src/thread_debug.h
Labels: Introduced in 2.80X, Introduced in 2.81X, bug
