Repository AliceLR/megazeux, pull requests merged in 2020-05, with the labels that each got.

#223 Add C++ unit tests for parts of MZX inaccessible to test worlds
  .gitignore
  Makefile
  arch/compat.inc
  src/editor/stringsearch.c
  src/io/memfile.h
  testworlds/run.sh
  unit/Makefile.in
  unit/Unit.hpp
  unit/align.cpp
  unit/editor/stringsearch.cpp
  unit/expr.cpp
  unit/io/bitstream.cpp
  unit/io/memfile.cpp
  unit/io/path.cpp
  unit/memcasecmp.cpp
Labels: Platform: All (native), enhancement

#235 Fix clang version detection for OpenBSD
  arch/compat.inc
  unit/Makefile.in
  unit/io/memfile.cpp
Labels: Introduced in 2.92X, Platform: OpenBSD, bug

#238 Updated MSVC project for 2.92d.
  arch/msvc/Core.vcxproj
  arch/msvc/Core.vcxproj.filters
  arch/msvc/Editor.vcxproj
  arch/msvc/Editor.vcxproj.filters
  arch/msvc/msvc.h
  src/io/memfile.h
Labels: Platform: Windows, enhancement

#239 Updated the Xcode project for 2.92d.
  arch/xcode/MZXRun/Info.plist
  arch/xcode/MegaZeux.xcodeproj/project.pbxproj
  arch/xcode/MegaZeux/Info.plist
Labels: Platform: MacOS, enhancement

#240 HTML5 port fixes for Emscripten >=1.39.5 and SDL 2.0.10
  arch/emscripten/Makefile.in
  arch/emscripten/web/res/index.html
  src/render_sdl.c
Labels: Status: dependency flaw, bug

#241 Added Safari support to the Emscripten build.
  arch/emscripten/web/res/mzxrun_loader.js
  src/audio/audio_sdl.c
Labels: Introduced in 2.92X, Platform: Emscripten, bug

#242 Improve config file validation for most settings, fix config bugs
  config.txt
  docs/changelog.txt
  src/configure.c
  src/configure.h
  src/editor/configure.c
  src/editor/configure.h
  src/editor/edit.c
  src/event.c
  src/event.h
  src/event_sdl.c
  src/graphics.c
  src/graphics.h
  src/main.c
  src/render.c
  src/render_gl.c
  src/render_gl.h
  src/render_gl2.c
  unit/Makefile.in
  unit/Unit.hpp
  unit/configure.cpp
Labels: Introduced in 2.80X, Platform: All, bug, enhancement

#243 Use config setting registry instead of separate set_config functions
  docs/changelog.txt
  src/configure.c
  src/configure.h
  src/editor/configure.c
  src/editor/configure.h
  src/editor/edit.c
  src/main.c
  src/run_stubs.c
  src/run_stubs.h
  src/world.c
  unit/Makefile.in
  unit/Unit.hpp
  unit/configure.cpp
Labels: Introduced in 2.82X, Platform: All, bug
