Repository AliceLR/megazeux, pull requests merged in 2020-04, with the labels that each got.

#221 Move various io-related source files to src/io/
  arch/emscripten/Makefile.in
  arch/emscripten/emzip.c
  src/Makefile.in
  src/audio/audio.c
  src/audio/audio_modplug.cpp
  src/board.c
  src/configure.c
  src/counter.c
  src/editor/Makefile.in
  src/editor/board.c
  src/editor/debug.c
  src/editor/robo_debug.c
  src/editor/robo_ed.c
  src/editor/stringsearch.c
  src/editor/stringsearch.h
  src/editor/world.c
  src/game.c
  src/hashtable.h
  src/io/bitstream.h
  src/io/dir.c
  src/io/dir.h
  src/io/fsafeopen.c
  src/io/fsafeopen.h
  src/io/memfile.h
  src/io/vfile.c
  src/io/vfile.h
  src/io/vfile_posix.h
  src/io/vfile_win32.h
  src/io/zip.c
  src/io/zip.h
  src/io/zip_deflate.h
  src/io/zip_deflate64.h
  src/io/zip_dict.h
  src/io/zip_implode.h
  src/io/zip_reduce.h
  src/io/zip_shrink.h
  src/io/zip_stream.c
  src/io/zip_stream.h
  src/legacy_rasm.c
  src/legacy_world.c
  src/memcasecmp.h
  src/mzm.c
  src/rasm.c
  src/robot.c
  src/run_robot.c
  src/str.c
  src/util.c
  src/util.h
  src/utils/Makefile.in
  src/utils/checkres.c
  src/utils/downver.c
  src/utils/hlp2html.c
  src/window.c
  src/world.c
  src/world_format.h
  src/world_struct.h
Labels: Platform: All, enhancement

#225 Fix memcasecmp alignment issues
  docs/changelog.txt
  src/counter_struct.h
  src/hashtable.h
  src/io/zip.h
  src/memcasecmp.h
  src/str.c
Labels: Platform: All, bug

#226 Refactor path functions out of util.c
  docs/changelog.txt
  src/Makefile.in
  src/audio/ext.c
  src/configure.c
  src/editor/char_ed.c
  src/editor/edit.c
  src/editor/robo_ed.c
  src/io/fsafeopen.c
  src/io/path.c
  src/io/path.h
  src/main.c
  src/render_glsl.c
  src/updater.c
  src/util.c
  src/util.h
  src/utils/Makefile.in
  src/utils/checkres.c
  src/utils/downver.c
  src/utils/hlp2html.c
  src/utils/utils_alloc.h
  src/window.c
  src/world.c
Labels: Platform: All, enhancement

#227 Remove util.h mem_* functions
  src/editor/edit.c
  src/legacy_robot.c
  src/legacy_robot.h
  src/mzm.c
  src/mzm.h
  src/old/legacy_save.c
  src/old/legacy_save.h
  src/run_robot.c
  src/util.c
  src/util.h
Labels: Platform: All

#229 Pulled in upstream libxmp MOD validation behavior
  contrib/libxmp/src/loaders/mod_load.c
  contrib/patches/libxmp/17-libxmp-4.4.1-reduce-mod-pattern-restrictions.patch
  contrib/patches/libxmp/README
Labels: Introduced in 2.90X, Platform: All, bug

#228 fsafetranslate unambiguous SFNs to their expanded filenames
  docs/changelog.txt
  src/io/fsafeopen.c
  src/io/fsafeopen.h
  testworlds/2.92/d01 fsafetranslate SFN.mzx
Labels: Introduced in 2.80X, Platform: All, bug, enhancement

#230 Improve flash thing behavior in SMZX and in normal mode edge cases
  docs/changelog.txt
  src/editor/edit.c
  src/editor/graphics.c
  src/editor/graphics.h
  src/graphics.c
  src/graphics.h
Labels: Platform: All, enhancement

#231 Replace Android build scripts + misc.
  .gitignore
  Makefile
  arch/android/CONFIG.ANDROID
  arch/android/Makefile.deps
  arch/android/Makefile.in
  arch/android/README
  arch/android/README.md
  arch/android/config_types.h
  arch/android/libogg-Android.mk
  arch/android/libvorbis-Android.mk
  arch/android/project/app/build.gradle
  arch/android/project/app/release/output.json
  arch/android/project/app/src/main/AndroidManifest.xml
  arch/android/project/app/src/main/java/net/digitalmzx/megazeux/GameActivity.java
  arch/android/project/app/src/main/java/net/digitalmzx/megazeux/MainActivity.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDevice.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLActivity.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
  arch/android/project/app/src/main/res/raw/readme
  arch/android/project/build.gradle
  arch/android/project/gradle/wrapper/gradle-wrapper.properties
  docs/changelog.txt
  src/event_sdl.c
  src/main.c
  src/platform_sdl.c
Labels: Platform: Android, enhancement

#232 Fixed memory leaks and added checked allocs to ccv
  src/utils/ccv.c
Labels: Introduced in 2.90X, Platform: All (native), bug

#233 Fix warnings for GCC 10
  src/editor/block.c
  src/error.c
  src/utils/ccv.c
  src/utils/checkres.c
  src/utils/hlp2html.c
Labels: Platform: All, bug

#234 Relicense Emscripten frontend to MIT license
  arch/emscripten/web/res/mzxrun_loader.js
  arch/emscripten/web/src/index.js
  arch/emscripten/web/src/storage.js
  arch/emscripten/web/src/storage_emscripten.js
  arch/emscripten/web/src/util.js
  arch/emscripten/web/src/zip.js
Labels: Platform: Emscripten, enhancement
