Repository AliceLR/megazeux, pull requests merged in 2020-03, with the labels that each got.

#211 Refactor render_layer_code to C++, add optimizations
  Makefile
  arch/compat.inc
  docs/changelog.txt
  src/old/render_layer_code.h
  src/render_layer.cpp
  src/render_layer_code.hpp
Labels: Platform: All, enhancement

#205 fix counter char writes on certain renderers when BYTE >= 14
  src/counter.c
Labels: Platform: All, bug

#212 Fix CHAR_BYTE writes on BYTE>=14, add compatibility for older versions
  docs/changelog.txt
  src/counter.c
  testworlds/2.80/012 BYTE 14.mzx
  testworlds/2.92/c02 BYTE 14.mzx
Labels: Platform: All, bug

#210 Add Windows UTF-8 compatibility layer for stdio/dirent functions
  arch/msvc/dirent.h
  docs/changelog.txt
  src/Makefile.in
  src/caption.c
  src/dir.c
  src/dir.h
  src/editor/block.c
  src/editor/buffer.c
  src/editor/char_ed.c
  src/editor/edit_di.c
  src/editor/edit_menu.c
  src/editor/param.c
  src/editor/undo.c
  src/editor/world.c
  src/error.c
  src/fsafeopen.c
  src/game_menu.c
  src/game_ops.c
  src/game_player.c
  src/game_update.c
  src/helpsys.c
  src/mzm.c
  src/settings.c
  src/sprite.c
  src/util.c
  src/util.h
  src/utils/Makefile.in
  src/vfs.c
  src/vfs.h
  src/vfs_posix.h
  src/vfs_win32.h
  src/window.c
  src/world_struct.h
Labels: Platform: Windows, enhancement

#214 Save Slots
  config.txt
  src/configure.c
  src/configure.h
  src/game.c
  src/window.c
  src/window.h
Labels: Platform: All, enhancement

#217 Properly handle SDL_TEXTINPUT, add event text buffer
  arch/3ds/keyboard.c
  arch/nds/event.c
  arch/wii/event.c
  docs/changelog.txt
  src/core.c
  src/core.h
  src/editor/edit.c
  src/editor/robo_ed.c
  src/editor/window.c
  src/event.c
  src/event.h
  src/event_sdl.c
  src/game.c
  src/intake.c
  src/intake_num.c
  src/window.c
Labels: Platform: All, bug, enhancement

#218 Add more file format documentation
  Makefile
  arch/install.inc
  docs/changelog.txt
  docs/fileform.html
  docs/filetypes/MZM3.md
  docs/old/mzm.txt
Labels: Platform: All, enhancement

#219 Decrease counter/string allocation sizes, fix signedness in lists
  docs/changelog.txt
  src/counter.c
  src/counter_struct.h
  src/editor/debug.c
  src/memfile.h
  src/mzm.c
  src/str.c
  src/world.c
Labels: Introduced in 2.80X, Platform: All, bug

#220 Fix khash 2^31 bug, cache hash values in key struct
  config.sh
  contrib/khash/khashmzx.h
  docs/changelog.txt
  src/Makefile.in
  src/counter.c
  src/counter_struct.h
  src/legacy_world.c
  src/str.c
  src/utils/checkres.c
  src/utils/hlp2html.c
  src/world.c
Labels: Platform: All, bug, enhancement
