Repository AliceLR/megazeux, pull requests merged in 2020-12, with the labels that each got.

#282 Update libxmp for LIBXMP_NO_PROWIZARD, misc. fixes.
  contrib/libxmp/Makefile.megazeux
  contrib/libxmp/docs/Changelog
  contrib/libxmp/include/xmp.h
  contrib/libxmp/src/common.h
  contrib/libxmp/src/control.c
  contrib/libxmp/src/format.c
  contrib/libxmp/src/format.h
  contrib/libxmp/src/hmn_extras.c
  contrib/libxmp/src/load.c
  contrib/libxmp/src/loaders/669_load.c
  contrib/libxmp/src/loaders/far_load.c
  contrib/libxmp/src/loaders/gdm_load.c
  contrib/libxmp/src/loaders/it_load.c
  contrib/libxmp/src/loaders/med3_load.c
  contrib/libxmp/src/loaders/med4_load.c
  contrib/libxmp/src/loaders/mmd1_load.c
  contrib/libxmp/src/loaders/mtm_load.c
  contrib/libxmp/src/loaders/okt_load.c
  contrib/libxmp/src/loaders/s3m_load.c
  contrib/libxmp/src/loaders/ult_load.c
  contrib/libxmp/src/med_extras.c
  contrib/libxmp/src/player.c
  contrib/libxmp/src/read_event.c
Labels: Platform: All, bug

#247 3ds: support for 800x240 mode, minor improvements
  arch/3ds/Makefile.in
  arch/3ds/README
  arch/3ds/README.md
  arch/3ds/banner/megazeux-banner.png
  arch/3ds/banner/megazeux.rsf
  arch/3ds/banner/silence.wav
  arch/3ds/event.h
  arch/3ds/keyboard.c
  arch/3ds/keyboard.h
  arch/3ds/platform.c
  arch/3ds/platform.h
  arch/3ds/render.cpp
  arch/3ds/render.h
  arch/3ds/romfs/kbd_display.png
Labels: Platform: Nintendo 3DS, enhancement

#283 Allow layer MZM object type selection during editor MZM import.
  docs/changelog.txt
  src/editor/block.c
  src/editor/block.h
  src/editor/edit.c
  src/mzm.c
  src/mzm.h
  src/run_robot.c
Labels: Platform: All, enhancement

#285 Implement vfile.c missing features/fixes and add unit tests.
  src/io/memfile.h
  src/io/vfile.c
  src/io/vfile.h
  unit/Makefile.in
  unit/Unit.hpp
  unit/io/memfile.cpp
  unit/io/vfile.cpp
Labels: Introduced in 2.92X, Platform: All, bug
