Repository AliceLR/megazeux, pull requests merged in 2021-04, with the labels that each got.

#295 Add Cocoa clipboard handler to replace Carbon/SDL2 handlers for Mac OS.
  arch/xcode/MegaZeux.xcodeproj/project.pbxproj
  src/editor/Makefile.in
  src/editor/clipboard_cocoa.m
Labels: bug

#296 Fix Xcode ansi.c/h, AppKit.framework, and USE_HEADERMAP issues.
  arch/xcode/MegaZeux.xcodeproj/project.pbxproj
Labels: Platform: MacOS, bug

#297 Add intake2 events, unit test, remove intake2 draw/click handlers.
  docs/changelog.txt
  src/editor/robo_ed.c
  src/graphics.h
  src/intake.c
  src/intake.h
  unit/Makefile.in
  unit/intake.cpp
Labels: Introduced in 2.91X, Platform: All, enhancement

#298 Implement robot editor undo/redo.
  docs/changelog.txt
  src/editor/robo_ed.c
  src/editor/robo_ed.h
  src/editor/undo.c
  src/editor/undo.h
  src/intake.c
  unit/intake.cpp
Labels: Platform: All, enhancement

#293 Add experimental extmem.c compression implementation.
  arch/nds/CONFIG.NDS
  arch/nds/extmem.c
  arch/nds/extmem.h
  arch/psp/CONFIG.PSP
  config.sh
  docs/changelog.txt
  src/Makefile.in
  src/board.c
  src/board_struct.h
  src/editor/board.c
  src/editor/debug.c
  src/editor/edit.c
  src/extmem.c
  src/extmem.h
  src/legacy_board.c
  src/robot.c
  src/robot.h
  src/run_robot.c
  src/world.c
Labels: Platform: Nintendo DS, Platform: PlayStation Portable, enhancement

#301 Add mzxout and mzxerr, use instead of freopen for stdio redirect.
  docs/changelog.txt
  src/audio/audio_openmpt.c
  src/core.c
  src/error.c
  src/legacy_rasm.c
  src/main.c
  src/network/HTTPHost.cpp
  src/network/Host.cpp
  src/nostdc++.cpp
  src/render_glsl.c
  src/render_layer_code.hpp
  src/str.c
  src/util.c
  src/util.h
  src/utils/checkres.c
  src/utils/utils_alloc.h
  src/world.c
Labels: Introduced in 2.92X, Platform: Nintendo DS, bug

#292 NDS port improvements: 2021 edition
  arch/nds/README
  arch/nds/arm7/source/arm7main.c
  arch/nds/audio.c
  arch/nds/extmem.c
  arch/nds/internals_notes.txt
  arch/nds/malloc_opts.h
  arch/nds/platform.h
  arch/nds/render.c
  docs/changelog.txt
  src/compat.h
  src/io/vio_posix.h
Labels: Platform: Nintendo DS, enhancement

#302 Reuse zstreams between files when reading/writing ZIP archives.
  src/io/zip.c
  src/io/zip.h
  src/io/zip_deflate.h
  src/io/zip_deflate64.h
  src/io/zip_implode.h
  src/io/zip_reduce.h
  src/io/zip_shrink.h
  src/io/zip_stream.c
  src/io/zip_stream.h
  unit/io/zip.cpp
Labels: Platform: All, Platform: Nintendo DS, enhancement

#254 Improve GLSL renderer compatibility with GLES and older cards.
  arch/android/CONFIG.ANDROID
  arch/android/README.md
  assets/glsl/tilemap.frag
  assets/glsl/tilemap.smzx.frag
  docs/changelog.txt
  src/configure.c
  src/render_glsl.c
Labels: Platform: All, enhancement
