Repository AliceLR/megazeux, pull requests merged in 2022-01, with the labels that each got.

#346 Add a MemorySanitizer action + required improvements/fixes.
  .github/workflows/main.yml
  Makefile
  config.sh
  src/error.c
  src/graphics.c
  src/graphics.h
  src/render_sdl.c
  src/render_soft.c
  src/run_robot.c
  unit/Makefile.in
Labels: bug

#340 Update Android dependencies and build script.
  arch/android/Makefile.deps
  arch/android/config_types.h
  arch/android/project/app/build.gradle
  arch/android/project/app/src/main/AndroidManifest.xml
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
  arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDL.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLActivity.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
  arch/android/project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
  arch/android/project/build.gradle
  arch/android/project/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, Platform: Android

#342 Overhaul graphics.c string functions and allow colors in scrolls.
  docs/changelog.txt
  src/editor/char_ed.c
  src/editor/debug.c
  src/editor/pal_ed.c
  src/editor/robo_ed.c
  src/graphics.c
  src/graphics.h
  src/intake.c
  src/robot.c
  src/scrdisp.c
Labels: enhancement, Platform: All
