Repository AliceLR/megazeux, pull requests merged in 2023-12, with the labels that each got.

#391 NDS, PSP, DOS: use Z_BEST_SPEED as the zip compression level.
  docs/changelog.txt
  src/io/zip.c
  src/io/zip.h
  src/io/zip_deflate.h
Labels: enhancement, Platform: Nintendo DS, Platform: PlayStation Portable, Platform: DOS

#356 World file format changes for MegaZeux 2.93.
  docs/changelog.txt
  docs/fileform.html
  src/audio/sfx.c
  src/audio/sfx.h
  src/counter.c
  src/editor/debug.c
  src/editor/sfx_edit.c
  src/editor/world.c
  src/graphics.c
  src/graphics.h
  src/legacy_world.c
  src/robot.c
  src/run_robot.c
  src/utils/checkres.c
  src/utils/downver.c
  src/world.c
  src/world.h
  src/world_format.h
  src/world_struct.h
  testworlds/1.00/006 firewalker_dur.mzx
  testworlds/1.00/006 firewalker_dur.txt
  testworlds/1.00/007 wind_dur.mzx
  testworlds/1.00/007 wind_dur.txt
  testworlds/2.51/012 Custom SFX.mzx
  testworlds/2.51/012 Custom SFX.txt
  testworlds/2.93/000 Format.mzx
  testworlds/2.93/001 Custom SFX.mzx
  testworlds/2.93/002 Custom SFX (old).mzx
  testworlds/2.93/003 FWRITE Mode Save Test.mzx
  testworlds/2.93/004 MZX Pal in SMZX Mode.mzx
  unit/Makefile.in
  unit/sfx.cpp
  version.inc
Labels: bug, enhancement, Introduced in 2.90X, Platform: All

#349 PS Vita port, take 2.
  .gitignore
  arch/psvita/CONFIG.PSVITA
  arch/psvita/Makefile.in
  arch/psvita/README.md
  arch/psvita/sce_sys/icon0.png
  arch/psvita/sce_sys/livearea/contents/bg.png
  arch/psvita/sce_sys/livearea/contents/startup.png
  arch/psvita/sce_sys/livearea/contents/template.xml
  config.sh
  docs/changelog.txt
  docs/platform_matrix.html
  src/configure.c
  src/event_sdl.c
  src/io/zip.c
  src/main.c
  src/render_layer.cpp
  src/settings.c
  src/util.c
  src/window.c
Labels: enhancement, Platform: PlayStation Vita

#392 Enable save slots by default on consoles.
  docs/changelog.txt
  src/configure.c
Labels: enhancement

#299 Add viewport_x, viewport_y, viewport_width, and viewport_height counters
  docs/changelog.txt
  docs/counter_list.txt
  src/counter.c
  testworlds/2.93/005 Viewport Counters.mzx
Labels: enhancement, Platform: All

#393 Add new counter DATE_WEEKDAY to get the system clock day of week.
  docs/changelog.txt
  docs/counter_list.txt
  src/counter.c
  src/editor/debug.c
  testworlds/2.93/006 DATE_WEEKDAY.mzx
Labels: enhancement

#359 nds: add BlocksDS port
  Makefile
  arch/nds-blocksds/CONFIG.NDS
  arch/nds-blocksds/Makefile.in
  arch/nds-blocksds/icon.png
  arch/nds/extmem.c
  arch/nds/extmem.h
  arch/nds/platform.c
  arch/nds/ram.c
  arch/nds/ram.h
  arch/nds/render.c
  config.sh
  src/compat.h
  src/window.c
Labels: enhancement

#396 Use window.c console parent directory hack for all platforms.
  src/window.c
Labels: enhancement

#397 Mobile display improvements for most HTML documentation.
  docs/changelog.txt
  docs/fileform.html
  docs/joystick.html
  docs/keycodes.html
  docs/platform_matrix.html
Labels: enhancement

#400 More fixes/tweaks for fileform.html and joystick.html.
  docs/fileform.html
  docs/joystick.html
Labels: bug

#398 Fix crashes caused by invalid Robotic items and conditions.
  docs/changelog.txt
  src/legacy_rasm.c
  testworlds/2.92/g19 Invalid Robotic Item.mzx
  testworlds/2.92/g20 Invalid Condition.mzx
Labels: bug, Introduced in 2.80X, Platform: All

#399 Add PLAYERDIED built-in label to detect player death.
  docs/changelog.txt
  src/game_update.c
  src/robot.c
  src/robot.h
  testworlds/2.93/007 playerdied.mzx
Labels: enhancement, Platform: All

#402 Add --host config.sh option and CROSS_COMPILE Makefile variable.
  Makefile
  arch/3ds/Makefile.in
  arch/amiga/Makefile.in
  arch/android/Makefile.in
  arch/compat.inc
  arch/darwin/Makefile.in
  arch/djgpp/Makefile.in
  arch/dreamcast/Makefile.in
  arch/emscripten/Makefile.in
  arch/gp2x/Makefile.in
  arch/mingw/Makefile.in
  arch/nds-blocksds/Makefile.in
  arch/nds/Makefile.in
  arch/nds/extmem.c
  arch/pandora/Makefile.in
  arch/psp/Makefile.in
  arch/psvita/Makefile.in
  arch/switch/Makefile.in
  arch/wii/Makefile.in
  arch/wiiu/Makefile.in
  config.sh
  contrib/icons/Makefile.in
  docs/changelog.txt
  src/configure.h
  src/io/vio.h
Labels: enhancement, Platform: Linux

#403 Fix dragon randomness, 1.x slimes, and reset/load on entry.
  docs/changelog.txt
  src/board.c
  src/board.h
  src/board_struct.h
  src/configure.c
  src/configure.h
  src/editor/board.c
  src/editor/configure.c
  src/editor/configure.h
  src/editor/edit_di.c
  src/game_update.c
  src/game_update_board.c
  src/legacy_board.c
  src/legacy_rasm.c
  src/utils/downver.c
  src/world.c
  src/world_format.h
  testworlds/1.00/008 slimeblob.mzx
  testworlds/1.00/008 slimeblob.txt
  testworlds/2.51/013 slimeblob.mzx
  testworlds/2.51/013 slimeblob.txt
  testworlds/2.90/015 No Reset same board.mzx
  testworlds/2.93/008 Dragon Random.mzx
  testworlds/2.93/009 Reset same board off.mzx
  testworlds/2.93/010 Reset same board on.mzx
  unit/configure.cpp
Labels: bug, Introduced in 2.80X, Introduced in 2.90X, Platform: All

#300 Add SPRn_AUTOOFF counters
  docs/changelog.txt
  docs/counter_list.txt
  docs/fileform.html
  src/counter.c
  src/editor/debug.c
  src/game_update.c
  src/sprite.h
  src/sprite_struct.h
  testworlds/2.93/011 SPRn_OFFONEXIT.mzx
Labels: enhancement, Platform: All

#401 Fix Vorbis loop detection for MOD_LOOPSTART > MOD_LOOPEND.
  docs/changelog.txt
  src/audio/audio_vorbis.c
Labels: bug, Introduced in 2.92X, Platform: All

#404 Changelog reformat, add changelog blurb for 2.93.
  docs/changelog.txt
Labels: enhancement, Platform: All

#407 Static sprites now collide relative to the viewport.
  docs/changelog.txt
  src/run_robot.c
  src/sprite.c
  src/sprite.h
  src/world.c
  src/world.h
  testworlds/2.65/004 Static Sprite Collision.mzx
  testworlds/2.65/004 Static Sprite Collision.txt
  testworlds/2.90/016 Static Sprite Collision.mzx
  testworlds/2.93/012 Static Sprite Collision.mzx
Labels: bug, Introduced in <=2.70, Platform: All

#408 Update WIPHelp.txt for MegaZeux 2.93.
  docs/WIPHelp.txt
Labels: enhancement, Platform: All
