Repository AliceLR/megazeux, pull requests merged in 2024-01, with the labels that each got.

#412 Fix testworlds PID check and ps edge case found using chroot.
  docs/changelog.txt
  testworlds/run.sh
Labels: bug, Platform: All (native), Introduced in 2.93X

#413 Fix license display for Darwin, simplify config.sh system dirs.
  arch/darwin/Makefile.in
  config.sh
  docs/changelog.txt
Labels: bug, Platform: MacOS, Introduced in 2.93X

#414 Improve the handling of optimization flags, add --enable-lto.
  Makefile
  arch/3ds/Makefile.in
  arch/emscripten/Makefile.in
  arch/switch/Makefile.in
  arch/wiiu/Makefile.in
  config.sh
  docs/changelog.txt
  unit/Makefile.in
Labels: enhancement, Platform: All

#415 Fix bugs related to setting a string splice to FREAD or FREADn.
  docs/changelog.txt
  src/str.c
  testworlds/2.81/002 String Splice Assignment.mzx
  testworlds/2.93/b01 String Splice Assignment.mzx
  testworlds/2.93/b02 String Splice FREAD Crash.mzx
Labels: bug, Introduced in 2.81X, Introduced in 2.82X, Platform: All

#416 Fix poor HTML5 vfilelength performance.
  docs/changelog.txt
  src/io/vio_posix.h
Labels: bug, Introduced in 2.82X, Platform: Emscripten

#406 3ds: Support building with SDL 1.2 and 2.x.
  arch/3ds/CONFIG.3DS
  arch/3ds/Makefile.in
  arch/3ds/pad.config.sdl12
  arch/3ds/pad.config.sdl2
  config.sh
  docs/platform_matrix.html
  src/Makefile.in
  src/configure.c
  src/event_sdl.c
  src/graphics.c
Labels: enhancement, Platform: Nintendo 3DS

#417 Replace --disable-libsdl2 with --enable-sdl(1,2).
  .github/workflows/main.yml
  Makefile
  arch/3ds/Makefile.in
  arch/darwin/README.md
  arch/mingw/Makefile.in
  arch/pandora/Makefile.in
  arch/psp/CONFIG.PSP
  arch/psp/Makefile.in
  arch/wii/Makefile.in
  arch/wii/README
  config.sh
  docs/changelog.txt
  src/Makefile.in
  src/editor/Makefile.in
  src/graphics.c
Labels: enhancement, Platform: All

#418 Preparation for SDL3 support.
  arch/msvc/config.h
  arch/xcode/MegaZeux.xcodeproj/project.pbxproj
  arch/xcode/config.h
  config.sh
  docs/changelog.txt
  src/SDLmzx.h
  src/about.c
  src/audio/audio_sdl.c
  src/audio/audio_wav.c
  src/audio/sampled_stream.cpp
  src/configure.c
  src/editor/clipboard_sdl2.c
  src/editor/clipboard_x11.c
  src/event_sdl.c
  src/graphics.c
  src/network/Socket.cpp
  src/network/server.cpp
  src/old/render_sdl2accel.c
  src/platform_endian.h
  src/platform_sdl.c
  src/platform_time.c
  src/render_gp2x.c
  src/render_sdl.c
  src/render_sdl.h
  src/render_soft.c
  src/render_softscale.c
  src/thread_sdl.h
  src/utils/checkres.c
  src/utils/hlp2html.c
  src/utils/y4m2smzx.c
Labels: enhancement, Platform: All

#420 SDL3 preparation (event_sdl.c).
  arch/switch/pad.config
  config.txt
  docs/changelog.txt
  docs/joystick.html
  src/configure.c
  src/configure.h
  src/event.h
  src/event_sdl.c
  src/platform_sdl.c
  unit/configure.cpp
Labels: enhancement, Platform: All

#421 Various SDL renderer-based renderer updates.
  .github/workflows/main.yml
  config.sh
  docs/changelog.txt
  src/Makefile.in
  src/graphics.c
  src/old/render_sdl2accel.c
  src/render_gl2.c
  src/render_sdl.c
  src/render_sdl.h
  src/render_sdlaccel.c
  src/render_softscale.c
  src/render_yuv.c
  src/renderers.h
  src/util.h
Labels: enhancement, Platform: All

#422 Add darwin-devel Github CI job.
  .github/workflows/main.yml
  src/utils/y4m2smzx.c
Labels: Platform: MacOS

#419 djgpp: Clean up render_svga.c, use vertical retrace palette/display flip
  arch/djgpp/render_svga.c
Labels: enhancement, Platform: DOS
