Repository AliceLR/megazeux, pull requests merged in 2024-04, with the labels that each got.

#430 Fix mfread and mfwrite handling for current>=end, warnings.
  docs/changelog.txt
  src/io/memfile.h
  src/io/zip.c
  unit/io/memfile.cpp
Labels: bug

#431 Fix bug where flash thing could display over the game UI layer.
  docs/changelog.txt
  src/editor/edit.c
Labels: bug, Platform: All, Introduced in 2.93X

#432 Clear world now resets the world compatibility version.
  docs/changelog.txt
  src/editor/edit.c
  src/editor/world.c
Labels: bug, Platform: All

#433 Fix HTTPHost::get failure for certain compressed files.
  docs/changelog.txt
  src/network/HTTPHost.cpp
  src/updater.cpp
Labels: bug, Platform: Windows

#428 nds-blocksds: Clean up/update Makefile, add GitHub CI support.
  .github/workflows/main.yml
  arch/nds-blocksds/Makefile.in
Labels: enhancement, Platform: Nintendo DS

#435 CI test
  .github/workflows/main.yml
Labels: Platform: Emscripten

#436 Fix CI for macos-14 runners.
  .github/workflows/main.yml
  docs/changelog.txt
  src/legacy_robot.c
Labels: Platform: MacOS

#437 Disable Emscripten CI cache.
  .github/workflows/main.yml
Labels: Platform: Emscripten
