Repository AliceLR/megazeux, pull requests merged in 2024-09, with the labels that each got.

#471 Fix darwin-dist Gatekeeper errors caused by bad codesign handling.
  arch/darwin/Makefile.in
  arch/darwin/MegaZeux.plist
  arch/darwin/bundle.sh
  arch/darwin/dmg.sh
  docs/changelog.txt
  scripts/deps/Makefile
Labels: bug, Platform: MacOS, Introduced in GIT

#472 Support UNC paths, Linux/macOS colon paths, reject colons in fsafetest.
  config.sh
  docs/changelog.txt
  src/io/fsafeopen.c
  src/io/path.c
  src/io/path.h
  src/io/vfs.c
  src/io/vio.c
  unit/io/path.cpp
  unit/io/vfs.cpp
Labels: enhancement, Platform: Windows, Platform: MacOS, Platform: Linux

#475 Update libxmp to 4.6.0+6cb48a4a.
  arch/msvc/Core.vcxproj
  arch/msvc/Core.vcxproj.filters
  arch/xcode/MegaZeux.xcodeproj/project.pbxproj
  contrib/libxmp/Makefile.megazeux
  contrib/libxmp/Makefile.megazeux-gen
  contrib/libxmp/README
  contrib/libxmp/docs/COPYING
  contrib/libxmp/docs/Changelog
  contrib/libxmp/src/common.h
  contrib/libxmp/src/control.c
  contrib/libxmp/src/filter.c
  contrib/libxmp/src/format.c
  contrib/libxmp/src/hio.c
  contrib/libxmp/src/hio.h
  contrib/libxmp/src/hmn_extras.c
  contrib/libxmp/src/lfo.c
  contrib/libxmp/src/load.c
  contrib/libxmp/src/loaders/amf_load.c
  contrib/libxmp/src/loaders/far_load.c
  contrib/libxmp/src/loaders/flt_load.c
  contrib/libxmp/src/loaders/iff.c
  contrib/libxmp/src/loaders/it.h
  contrib/libxmp/src/loaders/it_load.c
  contrib/libxmp/src/loaders/itsex.c
  contrib/libxmp/src/loaders/loader.h
  contrib/libxmp/src/loaders/mmd_common.c
  contrib/libxmp/src/loaders/mtm_load.c
  contrib/libxmp/src/loaders/s3m.h
  contrib/libxmp/src/loaders/s3m_load.c
  contrib/libxmp/src/loaders/sample.c
  contrib/libxmp/src/loaders/stm_load.c
  contrib/libxmp/src/loaders/xm.h
  contrib/libxmp/src/loaders/xm_load.c
  contrib/libxmp/src/md5.c
  contrib/libxmp/src/med_extras.c
  contrib/libxmp/src/memio.c
  contrib/libxmp/src/memio.h
  contrib/libxmp/src/mix_all.c
  contrib/libxmp/src/mixer.c
  contrib/libxmp/src/mixer.h
  contrib/libxmp/src/period.c
  contrib/libxmp/src/player.c
  contrib/libxmp/src/player.h
  contrib/libxmp/src/precomp_lut.h
  contrib/libxmp/src/read_event.c
  contrib/libxmp/src/rng.c
  contrib/libxmp/src/rng.h
  contrib/libxmp/src/scan.c
  contrib/patches/libxmp/03-libxmp-real-max-srate.patch
  docs/changelog.txt
Labels: bug, enhancement, Platform: All

#473 Misc. cleanup and fix patches for scripts/deps.
  arch/darwin/Makefile.in
  docs/changelog.txt
  scripts/deps/Makefile
  scripts/deps/Makefile.macos.in
  src/platform_endian.h
Labels: bug, enhancement, Platform: Windows, Platform: MacOS, Introduced in GIT

#426 Robotic 3: add counter and expression support to bracket interpolation.
  src/editor/robo_ed.c
  src/expr.c
  src/legacy_robot.c
  src/rasm.c
  src/robot.c
Labels: enhancement, Platform: All

#477 NOP invalid 1.x commands instead of treating them like END.
  src/legacy_rasm.c
Labels: bug, Platform: All, Introduced in 2.93X

#478 Fix TELEPORT command for 1.x.
  src/game.c
  src/run_robot.c
  src/world_struct.h
  testworlds/1.00/012 TELEPORT skip.mzx
  testworlds/1.00/012 TELEPORT skip.txt
  testworlds/2.51/017 TELEPORT noskip.mzx
  testworlds/2.51/017 TELEPORT noskip.txt
Labels: bug, Platform: All, Introduced in 2.93X

#479 Update gamecontrollerdb.txt to 6cc3a93e.
  assets/gamecontrollerdb.txt
Labels: enhancement, Platform: All

#481 Update most docs for MegaZeux 2.93b.
  README.md
  arch/dreamcast/render_fb.c
  arch/xcode/MZXRun/Info.plist
  arch/xcode/MegaZeux/Info.plist
  assets/help.fil
  config.txt
  docs/WIPHelp.txt
  docs/changelog.txt
  docs/fileform.html
  docs/joystick.html
  docs/keycodes.html
  docs/mzxhelp.html
  docs/platform_matrix.html
  scripts/buildscripts/mzx-scripts/version.sh
  testworlds/run.sh
  unit/Makefile.in
  unit/io/vio.cpp
  version.inc
Labels: Platform: All

#480 Enable link-time optimizations by default for most platforms.
  arch/3ds/CONFIG.3DS
  arch/android/CONFIG.ANDROID
  arch/djgpp/CONFIG.DJGPP
  arch/dreamcast/CONFIG.DC
  arch/emscripten/CONFIG.HTML5
  arch/nds-blocksds/CONFIG.NDS
  arch/nds/CONFIG.NDS
  arch/psvita/CONFIG.PSVITA
  arch/switch/CONFIG.SWITCH
  arch/wii/CONFIG.WII
  arch/wiiu/CONFIG.WIIU
  debian/rules
  docs/changelog.txt
  megazeux.spec
  scripts/buildscripts/mzx-scripts/platforms/windows-x64.sh
  scripts/buildscripts/mzx-scripts/platforms/windows-x86.sh
Labels: enhancement, Platform: All

#482 Debian changelog update for 2.93b
  debian/changelog
Labels: Platform: Linux

#484 3DS: force disable software on non-SDL configs.
  config.sh
  src/Makefile.in
  src/render_layer.cpp
Labels: bug, Platform: Nintendo 3DS, Introduced in 2.93X

#485 Fix show thing regression caused by overlay_mode fixes.
  docs/changelog.txt
  src/editor/edit.c
Labels: bug, Platform: All, Introduced in 2.93X
