Repository AliceLR/megazeux, pull requests merged in 2025-03, with the labels that each got.

#525 Debian changelog entries for 2.93c (also back-changed version numbers…
  debian/changelog
Labels: Platform: Linux

#526 Tweaks for BlocksDS port.
  arch/nds-blocksds/CONFIG.NDS
  arch/nds-blocksds/Makefile.in
  scripts/buildscripts/mzx-build.sh
  scripts/buildscripts/mzx-scripts/caverns.sh
  scripts/buildscripts/mzx-scripts/platforms/nds-blocksds.sh
  src/util.c
Labels: Platform: Nintendo DS

#527 Fix NDS date and time counters, fix remaining BlocksDS warnings.
  arch/nds-blocksds/Makefile.in
  arch/nds/arm7/source/arm7main.c
  arch/nds/render.c
  docs/changelog.txt
Labels: bug, Introduced in 2.84X, Platform: Nintendo DS

#528 Software layer renderer clipping and unaligned enhancements.
  docs/changelog.txt
  src/platform_endian.h
  src/render_layer.cpp
  src/render_layer_code.hpp
  src/render_layer_common.hpp
  unit/render.cpp
Labels: enhancement, Platform: All

#529 Remove bashisms and other issues from manifest.sh.
  arch/manifest.sh
  docs/changelog.txt
  scripts/buildscripts/mzx-scripts/crlf.sh
Labels: bug, enhancement, Introduced in 2.91X, Platform: All
